### ISSUE TITLE
False alarm - "Branch not merged" warning

### ISSUE THREAD

**Issue by clounie** [fork-dev/Tracker#216]
Today I did the following:

1. Merged a pull request from my PR branch into our `dev` branch
2. Deleted my PR branch on our `origin` remote
3. Tried to delete my PR branch locally

Fork warned me that my local branch was not merged, even though the local branch was at the second commit in this picture, and Fork clearly knew that origin/dev had the change.
![image](https://user-images.githubusercontent.com/11947182/36127890-d7a115f6-101c-11e8-9520-6898e0e8ba90.png)

I'm guessing it's because my local version of `dev` didn't have that change. 

I don't have a good solution to suggest at this point, but as a user it's not great when your git client tells you that you didn't merge something you *thought* you **had** merged.

**Comment by DanPristupov** [comment]
Git shows such a warning when your local branch is not on the _tip_ of corresponding remote branch or HEAD. That's why it says  _fully_ ('branch not _fully_ merged' if I remember correctly). I.e. 'the branches you are removing are not synchronized, please ensure everything is correct?'.

May be Fork can ignore this warning in a case whe feature branch is `behind` and 0 commits `ahead` it's upstream (i.e. has no unpushed changed). I'll check this out.

**Comment by nebhale** [comment]
This is a relatively new behavior from Git (last year or so I think), and as such I think it’s quite intentional.  I’d be careful having Fork diverge from the CLI’s behavior here.  I understand that you could improve the user experience, but I’m guessing that they added this for a reason; they must have been seeing people get burned by it.  And if it turns out that the community doesn’t like this behavior enough, the CLI will change it and Fork will get the change for free.

**Comment by DanPristupov** [comment]
@nebhale yes, I agree. Generally I prefer Fork to always behave like git. In this way it makes less confusion for both experienced users and switchers.

**Comment by clounie** [comment]
Yep.

Fair enough. Perhaps adding a message telling the user in effect "You don't have the local change, but origin does" to the error box could be a nice touch?

**Comment by seanparmelee** [comment]
I see this prompt daily. My workflow is similar to what was described above, but in the context of reviewing/testing teammates' PRs:

1. I check out a teammate's branch for local testing
2. PR is eventually merged
3. In Fork, I see that the visual indication that the remote tracking branch has been removed (love this btw!) so I go to delete my local branch.

Would it be possible to add a configuration option as to whether we want to see this prompt (default would be to show it, of course)? Not sure if you'd want such an option to apply to any time a branch is being deleting or specifically for the scenario where there used to be a remote tracking branch, but it has since been removed?

**Comment by AlbertBrand** [comment]
I also see this often. The team often uses a 'squash merge' when PRs are merged, so the original commits are gone. Would be really nice to have an option to disable the prompt.

**Comment by pkernevez** [comment]
We are using feature branch (ie I never work on master).
We use a 'merge' workflow and delete branch after merge, I saw the merged feature branch as an orphan (thank to the visual indication).
But every time I clean this old local feature branch I receive the same warning. It can't be merged in my HEAD as I'm never working on master, I'm on a feature branch that as been created before the merge and that most of the time hasn't already been rebased.
<img width="429" alt="image" src="https://user-images.githubusercontent.com/338699/130976773-73e405db-79b7-42c4-9ffe-6347621369d0.png">

This appends several times a day (for my own feature branches but also all my team branches I reviewed and checked out).

I understand that you prefer to avoid divergence with git, but you can add a configuration option to avoid this warning, and it will be decided by users.
You can limit the warning to branch that has been merge on origin.
May the reason for git to have this warning is to ensure that you executed a `git fetch` just before, but with fork I have the option 'automatically fetch', so for me the argument is not fully right in this case.

For me it's dangerous to keep the current behaviour because I stop reading warnings during deletion (it's normal to receive an alert), and I may miss an important one.
Even we drop a local branch by error, reflog is our friend :-)

**Comment by pkernevez** [comment]
It's also related to this issue: https://github.com/fork-dev/Tracker/issues/1141
