### ISSUE TITLE
Use /usr/local/bin/git first

### ISSUE THREAD

**Issue by swrobel** [fork-dev/Tracker#253]
I think most of us use homebrew, so it would be useful to use homebrew's git if it's installed as it's most likely to be what we're using at the command line

**Comment by tflo** [comment]
You can select the preferred git in the preferences, no?

![screen shot 2018-03-25 at 17 13 21-pty-fs8](https://user-images.githubusercontent.com/1410282/37876654-f8c70e0e-304f-11e8-995d-2a6561400d01.png)

– Tom

**Comment by DanPristupov** [comment]
> I think most of us use homebrew

Not really. I have some numbers:
93% use Fork git
5% use Apple git (part of Apple developer tools)
1% use homebrew git

To be honest I do NOT really want people to use homebrew git, because it makes the support much harder. More information there (second part): https://github.com/ForkIssues/Tracker/issues/69#issuecomment-316320705.

**Comment by tflo** [comment]
> 1% use homebrew git

Wow, that is astonishing! My guess would have been 30–40% or so.

> To be honest I do NOT really want people to use homebrew git, because it makes the support much harder.

That is understandable. But please do not remove the option to use the Homebrew git. If I really run into any compatibility issues with my latest Homebrew git and Fork, I can always set it to use the built-in git.

– Tom

**Comment by swrobel** [comment]
I had to browse to find it. Default options were just Apple & Fork git. So those numbers aren’t surprising given the effort required.
