### ISSUE TITLE
Performance Improvement and better memory management

### ISSUE THREAD

**Issue by aziz** [fork-dev/Tracker#28]
Fork is very well designed and featureful at the moment compared to the rest of git GUI apps.
What makes me still go to CLI or older GUIs like gitx is the speed and memory consumption. 

Fork still feels a bit slow and sluggish compared to simpler apps like GitX. if you could spend some time and improve the speed and performance it would be great and will pay back in near future.

**Comment by DanPristupov** [comment]
@aziz

I always split my week time between new features, improvement, bugfix and performance. Right now I think Fork's performance is quite good. What exactly is slower in your case?

P.S. I just checked. It looks like revision list scrolling in GitX is more responsible.

**Comment by aziz** [comment]
For me, the initial launch of the app in a big repo to checkout the changes, is considerably slower in fork compared to gitX.

**Comment by falsyvalues** [comment]
@DanPristupov memory usage is very high. macOS 10.13.6, 6 repos and over 1GB of memory usage.

**Comment by MichalBryxi** [comment]
Been using Fork happily on OSX for my personal & work projects for a bit.

But since one of the projects migrated to a monorepo (read: multiple git repositories collapsed to one) the responses of Fork are _not great_. Often times changing a branch takes _~10s_ or more to complete and several times I caught myself in some weird race condition where I changed branch and immediately tried to rebase (or something) and got in conflict with my previous action.

The details of the repo I'm talking about can't be published for obvious reasons, but there is no harm in sharing aggregate statistics:

```
❯ git count-objects -vH
count: 1013
size: 4.02 MiB
in-pack: 802432
packs: 1
size-pack: 327.24 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes

❯ git tag | wc -l
36771

❯ git branch --all | wc -l
578

❯ git rev-list --all --count
73432
```

I don't know whether these stats are useful for anything to give you a hint where the problem might be?

I was thinking about recreating the **structure** (in terms of same number of commits, tags, branches, overall repo size) of what we have and publishing it somewhere on github so that Fork authors can play with it, but I don't know whether it could be useful for anything?

Let me know if I can help in any way. Love your product.

**Comment by DanPristupov** [comment]
@MichalBryxi please show the results of:

`du -hs .`
`time git status --porcelain --untracked-files=all > /dev/null`
`time git for-each-ref refs/tags > /dev/null`

What you can do already:
1. `git gc`
2. View -> Hide tags (in Fork).

**Comment by maksimovic** [comment]
> View -> Hide tags (in Fork).

Oh my, how have I failed to notice this beautiful option?

**Comment by MichalBryxi** [comment]
This is a massive `npm` project so:

```
❯ du -hs .
3.1G	.

❯ time git status --porcelain --untracked-files=all > /dev/null
git status --porcelain --untracked-files=all > /dev/null  0.13s user 0.62s system 73% cpu 1.012 total

❯ time git for-each-ref refs/tags > /dev/null
git for-each-ref refs/tags > /dev/null  0.11s user 0.04s system 51% cpu 0.285 total
```

**Comment by DanPristupov** [comment]
@MichalBryxi You can **hide untracked files**, but you must remember to enable it when you add new files. This should significantly improve the performance. People with huge repos (like Chromium, ~30Gb) use it.
<img width="395" alt="Screen Shot 2020-11-20 at 11 02 45" src="https://user-images.githubusercontent.com/618115/99787350-ec196580-2b1f-11eb-8321-cc238d155c8c.png">

@maksimovic it can help a lot in repos with many tags.

**Comment by MichalBryxi** [comment]
Just a note for the author(s) and future travellers: Since in our repo we had huge number **~37k** of **tags**, the treatment with hiding tags from https://github.com/fork-dev/Tracker/issues/28#issuecomment-731019305 helped significantly and I don't think I need to chase the performance improvements any further for now.
Thank you 🙏
