### ISSUE TITLE
[Feature Request] Filter commits history by directory

### ISSUE THREAD

**Issue by umlx5h** [fork-dev/Tracker#304]
Hi.
I often structure project as follows.
```
foo/
  .git/
  frontend/
   ... big tree here
  backend/
   ... big tree here
  mobile/
   ... big tree here
```
I'd like to filter fork's commits history by specifying specific directory(path).
With command, We can do this by using `git log -- <path>`,  for example `git log -- frontend`

Thank you for awesome fork client!

**Comment by dan-tull** [comment]
Yes please! I just ran into this as well.

1. Browse to a folder in the "File Tree" tab of the lower panel.
2. Right click and choose "Show File History..."
3. Fork spins for a bit and then shows a blank panel where the commit history would go for a file.

I'm using a rather large repo as well and it would be very useful to be able to view the slice of commit history corresponding to a particular folder.

Arguably that this item is available in its current form as a right click on a folder is a bug, but rather than "fix" that by removing/disabling it in that context, I'd like it to show the commits for the folder.

**Comment by davidpsimons** [comment]
+1

I'd prefer the filtered view of the commit list rather than the modal history view

**Comment by davidpsimons** [comment]
@DanPristupov Does this being closed mean it's never going to happen, or is already done?

**Comment by DanPristupov** [comment]
We have a dedicated non-modal view on the sidebar:
<img width="345" alt="Screenshot 2021-03-18 at 08 53 44" src="https://user-images.githubusercontent.com/618115/111591220-74a2cc80-87c7-11eb-863c-6546626b79f4.png">

**Comment by davidpsimons** [comment]
Excellent, thank you!
