### ISSUE TITLE
"Stage" button not working with "ignore whitespace" enabled

### ISSUE THREAD

**Issue by mikchmie** [fork-dev/Tracker#360]
When "ignore whitespace" option is enabled, the floating "Stage" button (the one appearing in diff viewer when hovering over a hunk of code) doesn't work. Disabling "ignore whitespace" fixes the problem.

Steps to reproduce:
1. Make changes in repo (some whitespace only)
2. Open "Changes" view
3. Enable "Ignore whitespace"
3.a (optional). Select some lines
4. Press floating "Stage" button for given hunk of code / lines selection

Outcome: nothing happeans
Expected: selected changes are staged

Version 1.0.69.3 (macOS)

**Comment by DanPristupov** [comment]
I'm away from my computer now. I'll try to reproduce that issue when I'm back (in a week). Staging with ignore-whitespaces requires some additional actions, but I think I handled everything.

Dan Pristupov

**Comment by mikchmie** [comment]
I also cannot reproduce the issue, so it might have been fixed in one of hotfix updates.

By "staging selected changes" I mean staging with the "floating" button (see pictures attached) - which results in staging just a part of changes made to a given file (in opposite to staging the entire file).

<img width="643" alt="zrzut ekranu 2018-07-29 o 20 31 40" src="https://user-images.githubusercontent.com/15248837/43369439-b3497236-936e-11e8-956a-27cf18a7f3be.png">

<img width="610" alt="zrzut ekranu 2018-07-29 o 20 31 47" src="https://user-images.githubusercontent.com/15248837/43369441-b558bf64-936e-11e8-8fd9-c1a5d908c579.png">

**Comment by jmfederico** [comment]
I am having this issue.

I have a file with multiple changes. I enabled "Ignore whitespace" and when clicking "Stage" in any of the group of changes, nothing happens.

See attached screenshot.


<img width="1181" alt="screen shot 2018-11-06 at 13 54 39" src="https://user-images.githubusercontent.com/237977/48086826-c5539500-e1cb-11e8-8d7c-e3203f9da6d3.png">

**Comment by jmfederico** [comment]
This MIGHT be related to encoding (or special characters).

Sometimes it works, some others it doesn't. Haven't been able to know when it does, BUT see attached screenshot.

<img width="1176" alt="screen shot 2018-11-06 at 13 58 58" src="https://user-images.githubusercontent.com/237977/48087068-54f94380-e1cc-11e8-85fe-4055a8b2826b.png">

<img width="1177" alt="screen shot 2018-11-06 at 13 57 26" src="https://user-images.githubusercontent.com/237977/48087072-5a568e00-e1cc-11e8-9ac9-83f637d89310.png">

But this ONLY happens when ignore whitespace is enabled.

Should this be a separate issue?

**Comment by mikchmie** [comment]
The initial problem has been resolved, so I'm closing this issue.
