### ISSUE TITLE
Unable to use ssh-agent to sign into git repos

### ISSUE THREAD

**Issue by unikent-ms1** [fork-dev/Tracker#44]
With the command line git client, my ssh-agent running locally provides the authentication to the repository using my ssh public/private key. Fork doesn't seem to be able to cope with this and prompts for a password instead.

**Comment by DanPristupov** [comment]
What password Fork asks for?
- If it's a passphrase for SSH certificate, you should enter it once and then Fork will not ask it again (at least in Fork 1.0.48).
- If Fork asks for HTTPS credentials, it means that you use HTTPS url for your remote and you need to change it to SSH (you can check this with `git remote -v` terminal command).

P.S. Fork uses the default git-client and the default ssh-agent. Have you installed a custom one?

**Comment by unikent-ms1** [comment]
This was 1.0.48. The messaging says "Password" implying it's for the ssh access to the host and, even providing the passphrase for the ssh key, it still doesn't work. Apple supplied git and ssh-agents.

```
$ git --version
git version 2.3.2 (Apple Git-55)
```

ssh-agent doesn't seem to have a version parameter ;-)

```
$ ssh -V
OpenSSH_7.4p1, LibreSSL 2.5.0
```

**Comment by EntropyWorks** [comment]
I also have the same problem using my ssh-agent.  I'm using `gpg-agent` instead of `ssh-agent`. My SSH key is stored on a Yubikey device. 

`gpg-agent --daemon --enable-ssh-support --ignore-cache-for-signing --options /Users/atlas/.gnupg/gpg-agent.conf` 

Contents of my `.gnupg/gpg-agent.conf`
```
pinentry-program /usr/local/bin/pinentry-mac
enable-ssh-support
max-passphrase-days 360
write-env-file
use-standard-socket
default-cache-ttl-ssh 300
default-cache-ttl 0
max-cache-ttl 60
max-cache-ttl-ssh 720
```

I would expect to have `pinentry-mac` launch and prompt me for the Yubikey passphrase to unlock it. That never happens. If the Yubikey is unlocked already it should just act like any other `ssh-agent`.

**Comment by Cosaquee** [comment]
Any info about that? I use Yubikey for all ssh communication, including git. Would be nice if Fork would support such feature.

**Comment by vibechild** [comment]
This isn't really a Yubikey specific issue, and Fork doesn't need to do anything super complicated to fix this. It will also allow other types of agent forwarding to work in addition to the `gpg-agent` that Yubikey uses.

The problem is that the git client is not running in the standard shell environment, which means that it doesn't get the environment variables set - in particular `SSH_AUTH_SOCK`.

If Fork supported setting environment variables and passing them to git commands, this would be resolved.  It would also allow a lot of other customization.  

Here is how Tower handles it. It's not pretty, but you only have to do it once.
https://www.git-tower.com/help/mac/integration/environment

**Comment by DanPristupov** [comment]
@vibechild I think you can pass any environment variable to Fork by running it from command line.

**Comment by vibechild** [comment]
It's true - when I run:

```
SSH_AUTH_SOCK=/Users/XXXX/.gnupg/S.gpg-agent.ssh fork
```

From a bash shell, the Yubikey works fine.  I could make a bunch of aliases and not run fork from my command launcher or by clicking on it - but it would sure be nice if it could load the variables itself so I could use it like a normal app.

Unfortunately, this isn't as easy as reading in the `.bashrc` because it wouldn't work for `zsh` or `fish` users.  I'm not sure what the best way to do it would be.  I'd be fine with just a config file like Tower uses, but a preference tab like Textmate has would be pretty slick.

**Comment by DanPristupov** [comment]
@vibechild in *nix child application inherits environment from the parent process. So, just running Fork using `zsh` or `fish` should do the trick.

**Comment by PhilETaylor** [comment]
> So, just running Fork using zsh or fish should do the trick.

Running the command 

`/Applications/Fork.app/Contents/MacOS/Fork`

in a zsh shell works, but is a fudge and not a fix :)

**Comment by ysndr** [comment]
Wouldn't it be possible to add a setting for environment variables such as `SSH_AUTH_SOCK` as to my knowledge shell environments are distinct from the environments apps are opened with.

Edit: I see this has been suggested before, my bad :)

**Comment by wuifdesign** [comment]
You can run Fork as normal if you add the IdentityAgent to your `~/.ssh/config`:

```
Host *
  IdentityAgent /Users/XXX/.gnupg/S.gpg-agent.ssh
```

Replace "XXX" with your username!

**Comment by ysndr** [comment]
@wuifdesign Thank you very much, did not know about that config. It's working perfectly now!

**Comment by vibechild** [comment]
For me as well! Thank you for that.  This will make it much easier to use than the workaround of running it from terminal every time.  Thanks again!

**Comment by radiosilence** [comment]
@wuifdesign thanks! Also you can do `  IdentityAgent ~/.gnupg/S.gpg-agent.ssh`
