### ISSUE TITLE
Create a Github pull request by right-clicking a local branch

### ISSUE THREAD

**Issue by bdgeyter** [fork-dev/Tracker#48]
If a local branch is tracking a GitHub branch, you should be able to create a PR by right-clicking on that local branch, instead of finding the remote branch.

This feature is supported in SourceTree, for example. It's really useful when you have a large remote repository with lots of branches, where it's hard to find the specific branch.

**Comment by bdgeyter** [comment]
just noticed you can also create a PR by right-clicking on the latest commit that was pushed. Nice!!

**Comment by maksimovic** [comment]
I'd really like this as well, since I've got a lot of remote branches too.

Usually the list of my local branches is maybe 10-15 items long, which is way easier than going to the list of remotes (5+), expanding the list and finding the remote branch (or filtering, finding it, then cancelling the filter later)
