### ISSUE TITLE
[Feature Request] Merge without commit by holding Alt and Click on Merge button

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [fork-dev/Tracker#584]
It would be nice if it was possible to Merge without commit by clicking Merge button while holding alt button (on macOS) or similar. I tend to merge commit from develop to master but just merge in the reverse direction

**Comment by DanPristupov** [comment]
Not sure I understand you. Do you want `git merge --no-commit`? How is that related to 'reverse direction'?

Can rebase help you?

**Comment by tiagomsmagalhaes** [comment]
I haven't explained myself properly. Right now on merge you have a checkbox that asks us if we want to merge commit or not. I was asking if it was possible to have the Alt mechanic on the merge panel as you have on the changes window like "Commit and Push"

**Comment by DanPristupov** [comment]
The checkbox (`--no-ff`) remembers the last state, so I think saving 1 click doesn't really make sense.

You can create a custom action `git merge develop --no-ff` for that and execute it from the "Open in" drop down.

**Comment by tiagomsmagalhaes** [comment]
I'm always turning on or off so that's why I remembered the idea

I didn't noticed that feature (custom actions), or felt the need to use it

**Comment by edgraaff** [comment]
There are actually two things, maybe good to keep them separate.

One is the feature for being able merge with the `--no-commit` option, which would be very great. I use this a lot to review code of others, since it gives a short overview of what exactly _will_ change without actually applying it (yet).

The other feature is _how_ you would use it. If you'd ask me, I prefer a checkbox over holding a button while doing a merge (just like the `--no-ff` option). The difference is that the feature is visible at first sight, rather than having to know that you can hold Alt while doing the merge.
