### ISSUE TITLE
Custom actions Icon on dark theme

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [fork-dev/Tracker#586]
It's showing the light theme icon on dark theme i think.

macOS 10.13.6
Fork 1.0.75

![Screen Shot 2019-03-27 at 16 09 37](https://user-images.githubusercontent.com/5302040/55093005-8014fe80-50ab-11e9-8bd5-53295d31a73e.png)
![Screen Shot 2019-03-27 at 16 09 44](https://user-images.githubusercontent.com/5302040/55093006-80ad9500-50ab-11e9-87cd-ea17682a40e4.png)

**Comment by DanPristupov** [comment]
The problem doesn't exist in macOS 10.14 which provides the native theme.

I think I'll leave it as it is, because I'm going to disable dark theme in pre-Mojave versions in the near future.

**Comment by tiagomsmagalhaes** [comment]
any reasoning behind that that?

**Comment by DanPristupov** [comment]
The main reason is that I use Mojave and can't test Fork in other macOS versions.

Currently, Fork has 3 themes: light, dark and legacy-dark for macOS<10.14. The legacy theme is basically a dozen of hacks because previously macOS didn't support dark theme. A when I update it I can't even see the result.

**Comment by DanPristupov** [comment]
Same thing happened a while ago with tabs. Fork used to have tabbed interface from the beginning. Then Apple released native implementation which conflicted with the existing one. I waited until majority of users migrate to the new OS and then started using native tabs.
