### ISSUE TITLE
Git notifications slight odd sort order....

### ISSUE THREAD

**Issue by dceejay** [fork-dev/Tracker#81]
The sort order for git notifications seems odd - see image below.
Today is sorted badly then previous days in descending ok...

![image](https://user-images.githubusercontent.com/5375409/29638612-af8d6b0a-884f-11e7-92ca-6ca335db0018.png)

**Comment by DanPristupov** [comment]
Fork should the repositories from the following view: https://github.com/notifications?all=1 .

I'll investigate the problem and get back to you.

**Comment by DanPristupov** [comment]
@dceejay this seems to be a GitHub bug (or feature?).
Currently Fork displays items from the following view: https://github.com/notifications?all=1.
<img width="748" alt="2017-09-03 at 18 03" src="https://user-images.githubusercontent.com/618115/30004571-4b36083e-90d2-11e7-9f93-4e0e629fa67b.png">

Does anybody know if this order on GitHub is somehow intentional?
