### ISSUE TITLE
[Feature Request] Add support for MacBook Pro Touch Bar

### ISSUE THREAD

**Issue by uschmidt** [fork-dev/Tracker#87]
Add support for MacBook Pro Touch Bar with the ability to customize the Touch Bar controls

**Comment by DanPristupov** [comment]
@uschmidt I don't have the new MBP yet. I'm planning to buy it soon, or will try to use a touch bar emulator.

BTW, does anybody know if there's any big difference between last (2017) and previous (2016) MBP-T model?

**Comment by DanPristupov** [comment]
Surprisingly nobody cares about the touch bar support. After a year with the new MBP I still don't see any use in it :(

**Comment by natanrolnik** [comment]
@DanPristupov First of all, thanks for the app: every day I'm surprised by small details 😃
I would also love to see support for some common actions, like fetch, pull and push - this would be a small and great addition!

**Comment by amitav13** [comment]
I think we've come a long way since this was first raised...all programs that I use in my dev work - Android Studio, Intellij IDEA, VSCode, Firefox, Chrome - support touchbar controls. Even if we skip the option for customizations of controls, the common actions like @natanrolnik mentioned would be great to have.

**Comment by DanPristupov** [comment]
> After a year with the new MBP I still don't see any use in it :(

Neither did Apple, as it turned out.
